#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Preservados.Web.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Preservador")]
	public partial class DBPreservadosDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertQuestion(Question instance);
    partial void UpdateQuestion(Question instance);
    partial void DeleteQuestion(Question instance);
    #endregion
		
		public DBPreservadosDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["PreservadorConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBPreservadosDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBPreservadosDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBPreservadosDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBPreservadosDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Question> Questions
		{
			get
			{
				return this.GetTable<Question>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Questions")]
	public partial class Question : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _questionId;
		
		private string _QuestionTitle;
		
		private string _Question1;
		
		private string _Question2;
		
		private string _Question3;
		
		private string _Question4;
		
		private string _Answer;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnquestionIdChanging(int value);
    partial void OnquestionIdChanged();
    partial void OnQuestionTitleChanging(string value);
    partial void OnQuestionTitleChanged();
    partial void OnQuestion1Changing(string value);
    partial void OnQuestion1Changed();
    partial void OnQuestion2Changing(string value);
    partial void OnQuestion2Changed();
    partial void OnQuestion3Changing(string value);
    partial void OnQuestion3Changed();
    partial void OnQuestion4Changing(string value);
    partial void OnQuestion4Changed();
    partial void OnAnswerChanging(string value);
    partial void OnAnswerChanged();
    #endregion
		
		public Question()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_questionId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int questionId
		{
			get
			{
				return this._questionId;
			}
			set
			{
				if ((this._questionId != value))
				{
					this.OnquestionIdChanging(value);
					this.SendPropertyChanging();
					this._questionId = value;
					this.SendPropertyChanged("questionId");
					this.OnquestionIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuestionTitle", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string QuestionTitle
		{
			get
			{
				return this._QuestionTitle;
			}
			set
			{
				if ((this._QuestionTitle != value))
				{
					this.OnQuestionTitleChanging(value);
					this.SendPropertyChanging();
					this._QuestionTitle = value;
					this.SendPropertyChanged("QuestionTitle");
					this.OnQuestionTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Question1", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Question1
		{
			get
			{
				return this._Question1;
			}
			set
			{
				if ((this._Question1 != value))
				{
					this.OnQuestion1Changing(value);
					this.SendPropertyChanging();
					this._Question1 = value;
					this.SendPropertyChanged("Question1");
					this.OnQuestion1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Question2", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Question2
		{
			get
			{
				return this._Question2;
			}
			set
			{
				if ((this._Question2 != value))
				{
					this.OnQuestion2Changing(value);
					this.SendPropertyChanging();
					this._Question2 = value;
					this.SendPropertyChanged("Question2");
					this.OnQuestion2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Question3", DbType="NVarChar(50)")]
		public string Question3
		{
			get
			{
				return this._Question3;
			}
			set
			{
				if ((this._Question3 != value))
				{
					this.OnQuestion3Changing(value);
					this.SendPropertyChanging();
					this._Question3 = value;
					this.SendPropertyChanged("Question3");
					this.OnQuestion3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Question4", DbType="NVarChar(50)")]
		public string Question4
		{
			get
			{
				return this._Question4;
			}
			set
			{
				if ((this._Question4 != value))
				{
					this.OnQuestion4Changing(value);
					this.SendPropertyChanging();
					this._Question4 = value;
					this.SendPropertyChanged("Question4");
					this.OnQuestion4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Answer", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Answer
		{
			get
			{
				return this._Answer;
			}
			set
			{
				if ((this._Answer != value))
				{
					this.OnAnswerChanging(value);
					this.SendPropertyChanging();
					this._Answer = value;
					this.SendPropertyChanged("Answer");
					this.OnAnswerChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
